/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedMainRouteRouteImport } from './routes/_authed/_main/route'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedMainChannelsAtmeRouteRouteImport } from './routes/_authed/_main/channels/@me/route'
import { Route as AuthedMainChannelsServerIdRouteRouteImport } from './routes/_authed/_main/channels/$serverId/route'
import { Route as AuthedMainChannelsAtmeIndexRouteImport } from './routes/_authed/_main/channels/@me/index'
import { Route as AuthedMainChannelsServerIdIndexRouteImport } from './routes/_authed/_main/channels/$serverId/index'
import { Route as AuthedMainChannelsAtmeDmIdIndexRouteImport } from './routes/_authed/_main/channels/@me/$dmId/index'
import { Route as AuthedMainChannelsServerIdChannelIdIndexRouteImport } from './routes/_authed/_main/channels/$serverId/$channelId/index'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMainRouteRoute = AuthedMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMainChannelsAtmeRouteRoute =
  AuthedMainChannelsAtmeRouteRouteImport.update({
    id: '/channels/@me',
    path: '/channels/@me',
    getParentRoute: () => AuthedMainRouteRoute,
  } as any)
const AuthedMainChannelsServerIdRouteRoute =
  AuthedMainChannelsServerIdRouteRouteImport.update({
    id: '/channels/$serverId',
    path: '/channels/$serverId',
    getParentRoute: () => AuthedMainRouteRoute,
  } as any)
const AuthedMainChannelsAtmeIndexRoute =
  AuthedMainChannelsAtmeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedMainChannelsAtmeRouteRoute,
  } as any)
const AuthedMainChannelsServerIdIndexRoute =
  AuthedMainChannelsServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedMainChannelsServerIdRouteRoute,
  } as any)
const AuthedMainChannelsAtmeDmIdIndexRoute =
  AuthedMainChannelsAtmeDmIdIndexRouteImport.update({
    id: '/$dmId/',
    path: '/$dmId/',
    getParentRoute: () => AuthedMainChannelsAtmeRouteRoute,
  } as any)
const AuthedMainChannelsServerIdChannelIdIndexRoute =
  AuthedMainChannelsServerIdChannelIdIndexRouteImport.update({
    id: '/$channelId/',
    path: '/$channelId/',
    getParentRoute: () => AuthedMainChannelsServerIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/channels/$serverId': typeof AuthedMainChannelsServerIdRouteRouteWithChildren
  '/channels/@me': typeof AuthedMainChannelsAtmeRouteRouteWithChildren
  '/channels/$serverId/': typeof AuthedMainChannelsServerIdIndexRoute
  '/channels/@me/': typeof AuthedMainChannelsAtmeIndexRoute
  '/channels/$serverId/$channelId': typeof AuthedMainChannelsServerIdChannelIdIndexRoute
  '/channels/@me/$dmId': typeof AuthedMainChannelsAtmeDmIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/channels/$serverId': typeof AuthedMainChannelsServerIdIndexRoute
  '/channels/@me': typeof AuthedMainChannelsAtmeIndexRoute
  '/channels/$serverId/$channelId': typeof AuthedMainChannelsServerIdChannelIdIndexRoute
  '/channels/@me/$dmId': typeof AuthedMainChannelsAtmeDmIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/_main': typeof AuthedMainRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authed/_main/channels/$serverId': typeof AuthedMainChannelsServerIdRouteRouteWithChildren
  '/_authed/_main/channels/@me': typeof AuthedMainChannelsAtmeRouteRouteWithChildren
  '/_authed/_main/channels/$serverId/': typeof AuthedMainChannelsServerIdIndexRoute
  '/_authed/_main/channels/@me/': typeof AuthedMainChannelsAtmeIndexRoute
  '/_authed/_main/channels/$serverId/$channelId/': typeof AuthedMainChannelsServerIdChannelIdIndexRoute
  '/_authed/_main/channels/@me/$dmId/': typeof AuthedMainChannelsAtmeDmIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/channels/$serverId'
    | '/channels/@me'
    | '/channels/$serverId/'
    | '/channels/@me/'
    | '/channels/$serverId/$channelId'
    | '/channels/@me/$dmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/channels/$serverId'
    | '/channels/@me'
    | '/channels/$serverId/$channelId'
    | '/channels/@me/$dmId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_authed/_main'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authed/_main/channels/$serverId'
    | '/_authed/_main/channels/@me'
    | '/_authed/_main/channels/$serverId/'
    | '/_authed/_main/channels/@me/'
    | '/_authed/_main/channels/$serverId/$channelId/'
    | '/_authed/_main/channels/@me/$dmId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_main': {
      id: '/_authed/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedMainRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_main/channels/@me': {
      id: '/_authed/_main/channels/@me'
      path: '/channels/@me'
      fullPath: '/channels/@me'
      preLoaderRoute: typeof AuthedMainChannelsAtmeRouteRouteImport
      parentRoute: typeof AuthedMainRouteRoute
    }
    '/_authed/_main/channels/$serverId': {
      id: '/_authed/_main/channels/$serverId'
      path: '/channels/$serverId'
      fullPath: '/channels/$serverId'
      preLoaderRoute: typeof AuthedMainChannelsServerIdRouteRouteImport
      parentRoute: typeof AuthedMainRouteRoute
    }
    '/_authed/_main/channels/@me/': {
      id: '/_authed/_main/channels/@me/'
      path: '/'
      fullPath: '/channels/@me/'
      preLoaderRoute: typeof AuthedMainChannelsAtmeIndexRouteImport
      parentRoute: typeof AuthedMainChannelsAtmeRouteRoute
    }
    '/_authed/_main/channels/$serverId/': {
      id: '/_authed/_main/channels/$serverId/'
      path: '/'
      fullPath: '/channels/$serverId/'
      preLoaderRoute: typeof AuthedMainChannelsServerIdIndexRouteImport
      parentRoute: typeof AuthedMainChannelsServerIdRouteRoute
    }
    '/_authed/_main/channels/@me/$dmId/': {
      id: '/_authed/_main/channels/@me/$dmId/'
      path: '/$dmId'
      fullPath: '/channels/@me/$dmId'
      preLoaderRoute: typeof AuthedMainChannelsAtmeDmIdIndexRouteImport
      parentRoute: typeof AuthedMainChannelsAtmeRouteRoute
    }
    '/_authed/_main/channels/$serverId/$channelId/': {
      id: '/_authed/_main/channels/$serverId/$channelId/'
      path: '/$channelId'
      fullPath: '/channels/$serverId/$channelId'
      preLoaderRoute: typeof AuthedMainChannelsServerIdChannelIdIndexRouteImport
      parentRoute: typeof AuthedMainChannelsServerIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedMainChannelsServerIdRouteRouteChildren {
  AuthedMainChannelsServerIdIndexRoute: typeof AuthedMainChannelsServerIdIndexRoute
  AuthedMainChannelsServerIdChannelIdIndexRoute: typeof AuthedMainChannelsServerIdChannelIdIndexRoute
}

const AuthedMainChannelsServerIdRouteRouteChildren: AuthedMainChannelsServerIdRouteRouteChildren =
  {
    AuthedMainChannelsServerIdIndexRoute: AuthedMainChannelsServerIdIndexRoute,
    AuthedMainChannelsServerIdChannelIdIndexRoute:
      AuthedMainChannelsServerIdChannelIdIndexRoute,
  }

const AuthedMainChannelsServerIdRouteRouteWithChildren =
  AuthedMainChannelsServerIdRouteRoute._addFileChildren(
    AuthedMainChannelsServerIdRouteRouteChildren,
  )

interface AuthedMainChannelsAtmeRouteRouteChildren {
  AuthedMainChannelsAtmeIndexRoute: typeof AuthedMainChannelsAtmeIndexRoute
  AuthedMainChannelsAtmeDmIdIndexRoute: typeof AuthedMainChannelsAtmeDmIdIndexRoute
}

const AuthedMainChannelsAtmeRouteRouteChildren: AuthedMainChannelsAtmeRouteRouteChildren =
  {
    AuthedMainChannelsAtmeIndexRoute: AuthedMainChannelsAtmeIndexRoute,
    AuthedMainChannelsAtmeDmIdIndexRoute: AuthedMainChannelsAtmeDmIdIndexRoute,
  }

const AuthedMainChannelsAtmeRouteRouteWithChildren =
  AuthedMainChannelsAtmeRouteRoute._addFileChildren(
    AuthedMainChannelsAtmeRouteRouteChildren,
  )

interface AuthedMainRouteRouteChildren {
  AuthedMainChannelsServerIdRouteRoute: typeof AuthedMainChannelsServerIdRouteRouteWithChildren
  AuthedMainChannelsAtmeRouteRoute: typeof AuthedMainChannelsAtmeRouteRouteWithChildren
}

const AuthedMainRouteRouteChildren: AuthedMainRouteRouteChildren = {
  AuthedMainChannelsServerIdRouteRoute:
    AuthedMainChannelsServerIdRouteRouteWithChildren,
  AuthedMainChannelsAtmeRouteRoute:
    AuthedMainChannelsAtmeRouteRouteWithChildren,
}

const AuthedMainRouteRouteWithChildren = AuthedMainRouteRoute._addFileChildren(
  AuthedMainRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedMainRouteRoute: typeof AuthedMainRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedMainRouteRoute: AuthedMainRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
