/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedMainRouteRouteImport } from './routes/_authed/_main/route'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedMainDiscoverRouteRouteImport } from './routes/_authed/_main/discover/route'
import { Route as AuthedMainDiscoverIndexRouteImport } from './routes/_authed/_main/discover/index'
import { Route as AuthedMainChannelsAtmeRouteRouteImport } from './routes/_authed/_main/channels/@me/route'
import { Route as AuthedMainChannelsGuildIdRouteRouteImport } from './routes/_authed/_main/channels/$guildId/route'
import { Route as AuthedMainDiscoverServersIndexRouteImport } from './routes/_authed/_main/discover/servers/index'
import { Route as AuthedMainChannelsAtmeIndexRouteImport } from './routes/_authed/_main/channels/@me/index'
import { Route as AuthedMainChannelsGuildIdIndexRouteImport } from './routes/_authed/_main/channels/$guildId/index'
import { Route as AuthedMainChannelsAtmeDmIdIndexRouteImport } from './routes/_authed/_main/channels/@me/$dmId/index'
import { Route as AuthedMainChannelsGuildIdChannelIdIndexRouteImport } from './routes/_authed/_main/channels/$guildId/$channelId/index'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMainRouteRoute = AuthedMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMainDiscoverRouteRoute = AuthedMainDiscoverRouteRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthedMainRouteRoute,
} as any)
const AuthedMainDiscoverIndexRoute = AuthedMainDiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedMainDiscoverRouteRoute,
} as any)
const AuthedMainChannelsAtmeRouteRoute =
  AuthedMainChannelsAtmeRouteRouteImport.update({
    id: '/channels/@me',
    path: '/channels/@me',
    getParentRoute: () => AuthedMainRouteRoute,
  } as any)
const AuthedMainChannelsGuildIdRouteRoute =
  AuthedMainChannelsGuildIdRouteRouteImport.update({
    id: '/channels/$guildId',
    path: '/channels/$guildId',
    getParentRoute: () => AuthedMainRouteRoute,
  } as any)
const AuthedMainDiscoverServersIndexRoute =
  AuthedMainDiscoverServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthedMainDiscoverRouteRoute,
  } as any)
const AuthedMainChannelsAtmeIndexRoute =
  AuthedMainChannelsAtmeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedMainChannelsAtmeRouteRoute,
  } as any)
const AuthedMainChannelsGuildIdIndexRoute =
  AuthedMainChannelsGuildIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedMainChannelsGuildIdRouteRoute,
  } as any)
const AuthedMainChannelsAtmeDmIdIndexRoute =
  AuthedMainChannelsAtmeDmIdIndexRouteImport.update({
    id: '/$dmId/',
    path: '/$dmId/',
    getParentRoute: () => AuthedMainChannelsAtmeRouteRoute,
  } as any)
const AuthedMainChannelsGuildIdChannelIdIndexRoute =
  AuthedMainChannelsGuildIdChannelIdIndexRouteImport.update({
    id: '/$channelId/',
    path: '/$channelId/',
    getParentRoute: () => AuthedMainChannelsGuildIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof AuthedMainDiscoverRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/channels/$guildId': typeof AuthedMainChannelsGuildIdRouteRouteWithChildren
  '/channels/@me': typeof AuthedMainChannelsAtmeRouteRouteWithChildren
  '/discover/': typeof AuthedMainDiscoverIndexRoute
  '/channels/$guildId/': typeof AuthedMainChannelsGuildIdIndexRoute
  '/channels/@me/': typeof AuthedMainChannelsAtmeIndexRoute
  '/discover/servers': typeof AuthedMainDiscoverServersIndexRoute
  '/channels/$guildId/$channelId': typeof AuthedMainChannelsGuildIdChannelIdIndexRoute
  '/channels/@me/$dmId': typeof AuthedMainChannelsAtmeDmIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/discover': typeof AuthedMainDiscoverIndexRoute
  '/channels/$guildId': typeof AuthedMainChannelsGuildIdIndexRoute
  '/channels/@me': typeof AuthedMainChannelsAtmeIndexRoute
  '/discover/servers': typeof AuthedMainDiscoverServersIndexRoute
  '/channels/$guildId/$channelId': typeof AuthedMainChannelsGuildIdChannelIdIndexRoute
  '/channels/@me/$dmId': typeof AuthedMainChannelsAtmeDmIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/_main': typeof AuthedMainRouteRouteWithChildren
  '/_authed/_main/discover': typeof AuthedMainDiscoverRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_authed/_main/channels/$guildId': typeof AuthedMainChannelsGuildIdRouteRouteWithChildren
  '/_authed/_main/channels/@me': typeof AuthedMainChannelsAtmeRouteRouteWithChildren
  '/_authed/_main/discover/': typeof AuthedMainDiscoverIndexRoute
  '/_authed/_main/channels/$guildId/': typeof AuthedMainChannelsGuildIdIndexRoute
  '/_authed/_main/channels/@me/': typeof AuthedMainChannelsAtmeIndexRoute
  '/_authed/_main/discover/servers/': typeof AuthedMainDiscoverServersIndexRoute
  '/_authed/_main/channels/$guildId/$channelId/': typeof AuthedMainChannelsGuildIdChannelIdIndexRoute
  '/_authed/_main/channels/@me/$dmId/': typeof AuthedMainChannelsAtmeDmIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/channels/$guildId'
    | '/channels/@me'
    | '/discover/'
    | '/channels/$guildId/'
    | '/channels/@me/'
    | '/discover/servers'
    | '/channels/$guildId/$channelId'
    | '/channels/@me/$dmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/discover'
    | '/channels/$guildId'
    | '/channels/@me'
    | '/discover/servers'
    | '/channels/$guildId/$channelId'
    | '/channels/@me/$dmId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authed'
    | '/_authed/_main'
    | '/_authed/_main/discover'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_authed/_main/channels/$guildId'
    | '/_authed/_main/channels/@me'
    | '/_authed/_main/discover/'
    | '/_authed/_main/channels/$guildId/'
    | '/_authed/_main/channels/@me/'
    | '/_authed/_main/discover/servers/'
    | '/_authed/_main/channels/$guildId/$channelId/'
    | '/_authed/_main/channels/@me/$dmId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_main': {
      id: '/_authed/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedMainRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_main/discover': {
      id: '/_authed/_main/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthedMainDiscoverRouteRouteImport
      parentRoute: typeof AuthedMainRouteRoute
    }
    '/_authed/_main/discover/': {
      id: '/_authed/_main/discover/'
      path: '/'
      fullPath: '/discover/'
      preLoaderRoute: typeof AuthedMainDiscoverIndexRouteImport
      parentRoute: typeof AuthedMainDiscoverRouteRoute
    }
    '/_authed/_main/channels/@me': {
      id: '/_authed/_main/channels/@me'
      path: '/channels/@me'
      fullPath: '/channels/@me'
      preLoaderRoute: typeof AuthedMainChannelsAtmeRouteRouteImport
      parentRoute: typeof AuthedMainRouteRoute
    }
    '/_authed/_main/channels/$guildId': {
      id: '/_authed/_main/channels/$guildId'
      path: '/channels/$guildId'
      fullPath: '/channels/$guildId'
      preLoaderRoute: typeof AuthedMainChannelsGuildIdRouteRouteImport
      parentRoute: typeof AuthedMainRouteRoute
    }
    '/_authed/_main/discover/servers/': {
      id: '/_authed/_main/discover/servers/'
      path: '/servers'
      fullPath: '/discover/servers'
      preLoaderRoute: typeof AuthedMainDiscoverServersIndexRouteImport
      parentRoute: typeof AuthedMainDiscoverRouteRoute
    }
    '/_authed/_main/channels/@me/': {
      id: '/_authed/_main/channels/@me/'
      path: '/'
      fullPath: '/channels/@me/'
      preLoaderRoute: typeof AuthedMainChannelsAtmeIndexRouteImport
      parentRoute: typeof AuthedMainChannelsAtmeRouteRoute
    }
    '/_authed/_main/channels/$guildId/': {
      id: '/_authed/_main/channels/$guildId/'
      path: '/'
      fullPath: '/channels/$guildId/'
      preLoaderRoute: typeof AuthedMainChannelsGuildIdIndexRouteImport
      parentRoute: typeof AuthedMainChannelsGuildIdRouteRoute
    }
    '/_authed/_main/channels/@me/$dmId/': {
      id: '/_authed/_main/channels/@me/$dmId/'
      path: '/$dmId'
      fullPath: '/channels/@me/$dmId'
      preLoaderRoute: typeof AuthedMainChannelsAtmeDmIdIndexRouteImport
      parentRoute: typeof AuthedMainChannelsAtmeRouteRoute
    }
    '/_authed/_main/channels/$guildId/$channelId/': {
      id: '/_authed/_main/channels/$guildId/$channelId/'
      path: '/$channelId'
      fullPath: '/channels/$guildId/$channelId'
      preLoaderRoute: typeof AuthedMainChannelsGuildIdChannelIdIndexRouteImport
      parentRoute: typeof AuthedMainChannelsGuildIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthedMainDiscoverRouteRouteChildren {
  AuthedMainDiscoverIndexRoute: typeof AuthedMainDiscoverIndexRoute
  AuthedMainDiscoverServersIndexRoute: typeof AuthedMainDiscoverServersIndexRoute
}

const AuthedMainDiscoverRouteRouteChildren: AuthedMainDiscoverRouteRouteChildren =
  {
    AuthedMainDiscoverIndexRoute: AuthedMainDiscoverIndexRoute,
    AuthedMainDiscoverServersIndexRoute: AuthedMainDiscoverServersIndexRoute,
  }

const AuthedMainDiscoverRouteRouteWithChildren =
  AuthedMainDiscoverRouteRoute._addFileChildren(
    AuthedMainDiscoverRouteRouteChildren,
  )

interface AuthedMainChannelsGuildIdRouteRouteChildren {
  AuthedMainChannelsGuildIdIndexRoute: typeof AuthedMainChannelsGuildIdIndexRoute
  AuthedMainChannelsGuildIdChannelIdIndexRoute: typeof AuthedMainChannelsGuildIdChannelIdIndexRoute
}

const AuthedMainChannelsGuildIdRouteRouteChildren: AuthedMainChannelsGuildIdRouteRouteChildren =
  {
    AuthedMainChannelsGuildIdIndexRoute: AuthedMainChannelsGuildIdIndexRoute,
    AuthedMainChannelsGuildIdChannelIdIndexRoute:
      AuthedMainChannelsGuildIdChannelIdIndexRoute,
  }

const AuthedMainChannelsGuildIdRouteRouteWithChildren =
  AuthedMainChannelsGuildIdRouteRoute._addFileChildren(
    AuthedMainChannelsGuildIdRouteRouteChildren,
  )

interface AuthedMainChannelsAtmeRouteRouteChildren {
  AuthedMainChannelsAtmeIndexRoute: typeof AuthedMainChannelsAtmeIndexRoute
  AuthedMainChannelsAtmeDmIdIndexRoute: typeof AuthedMainChannelsAtmeDmIdIndexRoute
}

const AuthedMainChannelsAtmeRouteRouteChildren: AuthedMainChannelsAtmeRouteRouteChildren =
  {
    AuthedMainChannelsAtmeIndexRoute: AuthedMainChannelsAtmeIndexRoute,
    AuthedMainChannelsAtmeDmIdIndexRoute: AuthedMainChannelsAtmeDmIdIndexRoute,
  }

const AuthedMainChannelsAtmeRouteRouteWithChildren =
  AuthedMainChannelsAtmeRouteRoute._addFileChildren(
    AuthedMainChannelsAtmeRouteRouteChildren,
  )

interface AuthedMainRouteRouteChildren {
  AuthedMainDiscoverRouteRoute: typeof AuthedMainDiscoverRouteRouteWithChildren
  AuthedMainChannelsGuildIdRouteRoute: typeof AuthedMainChannelsGuildIdRouteRouteWithChildren
  AuthedMainChannelsAtmeRouteRoute: typeof AuthedMainChannelsAtmeRouteRouteWithChildren
}

const AuthedMainRouteRouteChildren: AuthedMainRouteRouteChildren = {
  AuthedMainDiscoverRouteRoute: AuthedMainDiscoverRouteRouteWithChildren,
  AuthedMainChannelsGuildIdRouteRoute:
    AuthedMainChannelsGuildIdRouteRouteWithChildren,
  AuthedMainChannelsAtmeRouteRoute:
    AuthedMainChannelsAtmeRouteRouteWithChildren,
}

const AuthedMainRouteRouteWithChildren = AuthedMainRouteRoute._addFileChildren(
  AuthedMainRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedMainRouteRoute: typeof AuthedMainRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedMainRouteRoute: AuthedMainRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
